export { ApiClient } from './client';
// TODO: Move this enum to the backend

export {
  UserStatus,
  Gender,
  Race,
  Title,
  UserRole,
  RoleFilter,
  RequisitionStatus,
  RequisitionHierarchy,
  AdvertStatus,
  AddressType,
  EducationLevel,
  Region,
  FinalGrade,
  AttachmentType,
  TypeIdentifier,
  WorkPlace,
  ApplicationStatus,
  EmploymentType,
  InterviewStatus,
  NotificationStatus,
  NotificationCategory,
  QuestionType,

} from '@gen/graphql';

export type {
  UserFragment,
  CreateUserInput,
  UpdateUserInput,
  CreateQuestionInput,
  UpdateQuestionInput,
  UpdateAttachmentInput,
  CreateRequisitionInput,
  ShortlistFilter,
  UpdateAdvertStatusInput,
  UpdateRequisitionInput,
  UpdateRequisitionStatusInput,
  CreateAdvertInput,
  AdvertFilter,
  RequisitionFilter,
  UpdateAddressInput,
  CreateAddressInput,
  UsersFilter,
  CreateAnswerInput,
  CreateEducationInput,
  UpdateEducationInput,
  CreateExperienceInput,
  UpdateExperienceInput,
  CreateContactInput,
  UpdateContactInput,
  ReadAllNotificationsInput,
  UpdateNotificationStatusInput,
  NotificationFilter,
  CreateApplicationInput,
  UpdateApplicationStatusInput,
  ApplicationFilter,
  CreateShortlistInput,
  CreateInterviewInput,
  ReScheduleInterviewInput,
  UpdateInterviewStatusInput,
  AddressFragment,
  AdvertFragment,
  PartialAdvertFragment,
  FullAdvertFragment,
  AnswerFragment,
  ApplicantFragment,
  FullApplicantFragment,
  ApplicationFragment,
  FullApplicationFragment,
  UploadAttachmentFragment,
  AttachmentFragment,
  FullAttachmentFragment,
  ContactFragment,
  EducationFragment,
  ExperienceFragment,
  InterviewFragment,
  NotificationFragment,
  PositionFragment,
  QuestionFragment,
  RequisitionFragment,
  FullRequisitionFragment,
  ShortlistFragment,
  UserFragmentDoc,
  FullUserFragment,
  CreateInterviewPackageInput,
  UpdateInterviewPackageInput,
  InterViewPackageFragment,
  FullInterViewPackageFragment,
  InterviewFilter,




} from '@gen/graphql';
